### ISSUE TITLE
Docs link takes to a Workplace specific page

### ISSUE THREAD

**Issue by mudrd8mz** [moodleworkplace/moodle-tool_certificate#51]
The link "More documentation on this plugin" in the plugins directory takes to https://docs.moodle.org/en/Certificates which is labelled with:

![image](https://user-images.githubusercontent.com/85831/95298023-b1af7e00-087b-11eb-95b1-2caad43bb391.png)

This may give impression that the modules do not work in vanilla Moodle, which is not correct.

**Comment by marinaglancy** [comment]
Thanks David. We changed the boilerplate, we now say that it is part of Moodle Workplace but also available as a plugin for Moodle LMS
