### ISSUE TITLE
Once the first certificate is issued, the global search index task starts to fail

### ISSUE THREAD

**Issue by mudrd8mz** [moodleworkplace/moodle-tool_certificate#53]
We are experiencing this serious problem on a production site after we started to use the Course certificate in a course.

Earlier today at 11:23 AM, the first Course certificate was issued on the site. Starting from 11:30 AM, the scheduled task "Global search indexing" stopped working, ending with a fatal error:

```

Execute scheduled task: Global search indexing (core\task\search_index_task)
--
Processing area: Chat - activity information
No new documents to index.
Processing area: Course custom fields
PHP Notice:  Undefined offset: 1 in /opt/app/course/classes/search/customfield.php on line 105
Default exception handler: Exception - Call to a member function get() on null Debug:
Error code: generalexceptionmessage
* line 110 of /course/classes/search/customfield.php: Error thrown
* line ? of unknownfile: call to core_course\search\customfield->get_document()
* line 103 of /lib/classes/dml/recordset_walk.php: call to call_user_func()
* line 72 of /search/classes/skip_future_documents_iterator.php: call to core\dml\recordset_walk->current()
* line 93 of /search/classes/skip_future_documents_iterator.php: call to core_search\skip_future_documents_iterator->current()
* line 235 of /search/classes/engine.php: call to core_search\skip_future_documents_iterator->valid()
* line 1153 of /search/classes/manager.php: call to core_search\engine->add_documents()
* line 59 of /lib/classes/task/search_index_task.php: call to core_search\manager->index()
* line 163 of /admin/tool/task/cli/schedule_task.php: call to core\task\search_index_task->execute()
 
!!! Exception - Call to a member function get() on null !!!
```

Debugging revealed problems with custom course fields and closer look into the database leads to `tool_certificate`.

We were not using custom course fields on the site. We had neither category nor a custom field in the database tables.

When the certificate was added into a course, it apparently created an `mdl_customfield_category` record with component set to "tool_certificate" and "area" set to "issue", and a few custom fields such as "Internal course ID used in URLs", "Course short name" etc. all in this category.

Note that none of these fields appear at Site administration > Courses > Course custom fields - maybe because that page only shows those in `core_course` component?

Anyway. Once that `core\task\search_index_task` task is running, the `core_course\search\customfield:: get_document()` is called with `$record` parameter containing a record with `fieldid` 1. But the `$handler->get_fields()` in that method (where `$handler = course_handler::create()` returns empty list. As a result, the `$field->get()` call at line no. 110 raises the reported error.

I know nothing about the custom course fields API so I can't really help more here. But for us this is a serious issue now. Thank you for any help with sorting it out.

**Comment by marinaglancy** [comment]
Hi David, thanks for the report, I can take a look but my gut feeling that it is a problem with global search.
This is not "custom course fields API", this is "custom fields API" - https://docs.moodle.org/dev/Custom_fields_API
Any component can use custom fields, so does tool_certificate.

**Comment by marinaglancy** [comment]
Indeed a core error. See https://tracker.moodle.org/browse/MDL-69902

**Comment by marinaglancy** [comment]
David, you can go to the /admin/tool/certificate/customfields.php as admin and delete a field with id=1 (it's the only one that can cause problems). the field will be automatically generated again
